language: node_js
node_js:
  - "7"
deploy:
  provider: heroku
  api_key:
    secure: qZTSQCmqQZKYNyvIb4QtDd7+jyHuLFSCceJTnYRBrrZLldrwj2h7iyN0UU8umz+V1DFdxFh2r7iEeRK5331RggWpLXBkaguEq+/syS/oRdkh/P1q7lUEknl32Loh25NIoYJAIvrjswFRxI7hvyegckyM00f+e/HnC5vFkr197/Djs00oTtKjU/Ljz5mGkcUPLIuYGfeUUq/9TBJx/93lu+giXj2lIL+BspnuksrJ8+SkdUZ51D6m2mdN7c2TS5MGomxJrIUO4Aijc0gRWZ3q7dlFdau5UMo/3gOTVQpWk7hmTsiUYRkQ+oN5Dk3D2WCdwkujk0cBqmRO3hKsIUzvDj6HH90zUKoJ1C5Yo+4bQ8ko3NGSR57F8i1xy7LG40Pz2I8WWh6BA91F91EO5oJNstsCuRTCzaqQ9LP5mIM/zaVvV7GtqEIOHE/0Q4zLCq2+xiycFf4pZs/GNcBWc29ElTYrBB0EuASTjPZYuz3Z6LxfyOSKEl6cPbSdxbrg3WpLqUuo7vOkuDSyuUwU4I60CpERBYv/g7bYoKQYT4/aCDakXM+cssutVwM85xxfhKnpMDELashwo3CbX0aZPZ+sDmiB5M5i3/RNFh7PeixJjE/iBToYhxkZdfrf8Htpyoo+ToB5t1fgw1AmOUiVfcrvotEMvqtCI+5dosgvUuwNIEY=
    app: intense-spire-55270
  on:
    repo: tiy-eric/react-marvel
